<?php
/**
 * Copyright © 2016 Magestore. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php /** @var $block \Magento\Sales\Block\Order\Info */ ?>
<?php $_order = $block->getOrder() ?>
<div class="block block-order-details-view">
    <div class="block-title">
        <strong><?php /* @escapeNotVerified */
            echo __('Order Information') ?></strong>
    </div>
    <div class="block-content">
        <?php if (!$_order->getIsVirtual()): ?>
            <div class="box box-order-shipping-address">
                <strong class="box-title"><span><?php /* @escapeNotVerified */
                        echo __('Shipping Address') ?></span></strong>
                <div class="box-content">
                    <address><?php /* @escapeNotVerified */
                        echo $block->getFormattedAddress($_order->getShippingAddress()); ?></address>
                </div>
            </div>

            <div class="box box-order-shipping-method">
                <strong class="box-title">
                    <span><?php /* @escapeNotVerified */
                        echo __('Shipping Method') ?></span>
                </strong>
                <div class="box-content">
                    <?php if ($_order->getShippingDescription()): ?>
                        <?php echo $block->escapeHtml($_order->getShippingDescription()) ?>
                    <?php else: ?>
                        <?php /* @escapeNotVerified */
                        echo __('No shipping information available'); ?>
                    <?php endif; ?>
                </div>
            </div>
        <?php endif; ?>
        <div class="box box-order-billing-address">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */
                    echo __('Billing Address') ?></span>
            </strong>
            <div class="box-content">
                <address><?php /* @escapeNotVerified */
                    echo $block->getFormattedAddress($_order->getBillingAddress()); ?></address>
            </div>
        </div>
        <div class="box box-order-billing-method">
            <strong class="box-title">
                <span><?php /* @escapeNotVerified */
                    echo __('Payment Method') ?></span>
            </strong>
            <div class="box-content">
                <?php echo $block->getPaymentInfoHtml() ?>
            </div>
        </div>
    </div>
</div>
<style>
    .box {
        width: 25%;
        float: left;
        display: block;
        overflow: auto;
    }

    .block-order-details-view {
        display: inline-block;
        border: 1px solid #c6c6c6;
        width: 100%;
        padding: 25px;
        box-sizing: border-box;
    }

    .block-content {
        width: 100%;
    }

    .block-title {
        border-bottom: 1px solid #c6c6c6;
        margin-bottom: 25px;
        padding-bottom: 10px;
    }

    .block-title > strong {
        font-size: 2.2rem;
        font-weight: 300;
    }

    .order-date {
        margin: 15px 0px;
    }

    .label, .label {
        font-weight: bold;
    }

    .account-info {
        width: 250px;
    }
</style>
